ServerlessLLM/ServerlessLLM

- README.md
Update README to provide Quickstart Guide for users to 1. deploy a serverless cluster or 2. use fast checkpoint loading.
> docs: add sllm-store guide

- README.md
- docs/stable/store/quickstart.md
- Update README to report speed-up since loading time depends on many factors.
- Fix warmup code in getting started document.
> docs: update readme and fix docs (#14)

- docs/stable/store/quickstart.md
- serverless_llm/store/README.md
This pull request adds README for how to build `sllm-store` from source.
> docs: build sllm-store from source

- serverless_llm/store/serverless_llm_store/__init__.py
- serverless_llm/store/serverless_llm_store/sllm_store.py
This PR support #26 by adding two interface
- save state dict: saves state dict directly without hf configurations
- load dict: load state dict to current GPU device
> Add save/load interface for vLLM

- docs/README.md
- docs/stable/intro.md
> chore: fix intro in docs

- docs/README.md
- docs/stable/intro.md
Fixed assets position in document, also update the README.md to show how to use images in the documents.
> chore: fix document assets position

- docs/stable/store/quickstart.md
Briefly describe your changes.
Explain why this change is needed and what problem it solves.
If it fixes an issue, link it (e.g., `close #123`).
> docs: add tips for usage with vllm

- .github/workflows/backend.yaml
- .github/workflows/cli_test.yaml
- .github/workflows/test_sllm_store.yaml
- serverless_llm/serve/backends/transformers_backend.py
- serverless_llm/store/csrc/server.cpp
This PR changes the GitHub Workflow to efficiently use self-hosted GPU runners.
> [test] Gpu workflow

- docs/stable/getting_started/installation.md
- docs/stable/store/quickstart.md
- serverless_llm/store/patch.sh
Add a script to apply serverless_llm vllm patch
Add a script to apply serverless_llm vllm patch
> fix: add script to apply patch

- .github/workflows/cli_test.yaml
- CONTRIBUTING.md
- Dockerfile
- Dockerfile.worker
- docs/stable/getting_started/installation.md
- docs/stable/store/quickstart.md
- serverless_llm/store/README.md
- serverless_llm/store/setup.py
Briefly describe your changes.
Explain why this change is needed and what problem it solves.
If it fixes an issue, link it (e.g., `close #123`).
> [URGENT] docs: update sllm_store to dev4

- docs/stable/store/quickstart.md
- serverless_llm/store/requirements.txt
- serverless_llm/store/serverless_llm_store/transformers.py
This PR includes the following updates:
1. Updates the documentation to ensure compatibility with the latest code.
2. Fixes the versions of `transformers` and `accelerate` to avoid dependency conflicts.
3. Resolves a bug in the transformer checkpoint loader.
Fixes issue #90.
> [FIX]: checkpoint loader for transformer backend

- .github/workflows/linters.yml
- CODE_OF_CONDUCT.md
- configs/.wordlist.txt
Add Code of Conduct adopted from the [Contributor Covenant](https://www.contributor-covenant.org/).
This change adds a standard Code of Conduct to foster a welcoming and inclusive community.
> docs: add code of conduct

- .github/workflows/publish.yml
- requirements.txt
- setup.py
- sllm_store/setup.py
> chore: update version to 0.5.1

- sllm_store/README.md
This PR addresses a minor typo in the `sllm_store/README.md` and improves the overall clarity and structure of the README.
NA
> Update `sllm-store` README.md

- configs/.wordlist.txt
- docs/stable/developer/_category_.json
- docs/stable/developer/supporting_a_new_hardware.md
Added a developer guide outlining criteria and steps to support new hardware for ServerlessLLM.
> docs: add developer guide

- blogs/serverless-llm-architecture/README.md
Adjusted the image size in the blog post for improved readability.
> docs: update README.md

- .github/workflows/rocm_build.yaml
- README.md
- docs/stable/store/installation_with_rocm.md
- sllm_store/README.md
+ Add CI for ROCm wheel build
+ Add news about ROCm support
+ Typo fix
+ Add CI for ROCm wheel build
> fix: CI for build rocm package

- README.md
- configs/.wordlist.txt
- docs/stable/intro.md
- docs/stable/store/installation_with_rocm.md
In the website's documentation, specify the type of hardware ServerlessLLM supports, emphasize that we support both NVIDIA and AMD GPU, and provide a link to the installation guide for AMD GPU.
It fixes the #150
> Specify supported hardware types and provide a link to AMD GPU

- requirements-worker.txt
Add GPUtil and speedtest-cli to requirements-worker.txt
Fix bug.
> fix: update requirements for worker to support the hardware information collector

- Dockerfile
- Dockerfile.worker
- sllm/serve/hardware_info_collector.py
- sllm/serve/store_manager.py
- sllm_store/csrc/server.cpp
- sllm_store/csrc/sllm_store/checkpoint_store.h
- sllm_store/proto/storage.proto
- sllm_store/sllm_store/client.py
This PR enhances the `SllmLocalStore` by addressing issues in the loading loop and adapting to the latest automatic hardware configuration detection feature.
- Fixes the first issue mentioned in #131.
- Prepares the codebase for the upcoming live-migration feature release.
> [FIX] Fix loading loop in `SllmLocalStore`

- setup.py
- sllm_store/setup.py
> chore: update version to 0.6.0

- Dockerfile
- Dockerfile.worker
- sllm_store/Dockerfile.builder
- sllm_store/Dockerfile.rocm
This PR refactors the Dockerfiles to improve build performance, compatibility, and maintainability:
- Switched the base image to Ubuntu 20.04 for better compatibility.
- Reorganized Dockerfile steps to enhance layer caching and reduce build times.
- Achieve faster build times through optimized caching.
- Improve compatibility as per suggestions in #164 by @lrq619.
Please review the changes, test the builds, and share feedback for any required adjustments!
> Refactor Dockerfiles for Improved Build Performance and Compatibility

- setup.py
- sllm_store/setup.py
> 0.6.1 release

- setup.py
- sllm_store/setup.py
This is an urgent release to fix the `pip install serverless-llm-store` bug.
Closes #203.
> release: v0.6.2

- sllm_store/setup.py
Update `setup.py` to make the CUDA_HOME/ROCM_HOME check error clearer.
Now we will import both `CUDA_HOME` and `ROCM_HOME` from `torch.utils.cpp_extension`, and raise an error when neither of them is detected.
As in #230, the error raised in compile `sllm_store` is unclear. It will raise a `hip not found` error when `CUDA_HOME` is not set.
> fix: update CUDA_HOME/ROCM_HOME installation check in sllm_store

- setup.py
- sllm_store/setup.py
Briefly describe your changes.
Explain why this change is needed and what problem it solves.
If it fixes an issue, link it (e.g., `close #123`).
> release 0.6.3

- docs/stable/community/meetups.md
Add lora fine tuning meetup slides in community page
> docs: add lora fine tuning meetup slides

- README.md
- docs/stable/community/talks.md
Update the link to the Serverless LLM tutorial and demo slides for the SESAME '25 workshop.
Closes #216.
> docs: update sesame tutorial slides
