ServerlessLLM/ServerlessLLM

examples/README.md

- This PR re-adds the `examples` folder.The `examples` folder is essential as the Dockerfile references it with the line `COPY examples examples`. 
- The folder includes a README file (`./examples/README.md`) that will be used to document example scripts for ServerlessLLM.

fix: re-add examples folder

---

serverless_llm/cli/sllm_cli.py
serverless_llm/cli/update.py
serverless_llm/serve/app_lib.py
serverless_llm/serve/controller.py
serverless_llm/serve/routers/roundrobin_router.py
serverless_llm/serve/routers/router_utils.py

+ This PR updates both the `serve` and `cli` components to add a feature that enables serverless LLM to update autoscaling configurations.
+ Users can now use `sllm-cli update --config newconfig.json` to updatae the configuration. The  format is same as deploy configuration, but only the autoscaling configuration will be updated.

feat: add support for update autoscaling config

---

serverless_llm/serve/backends/transformers_backend.py
serverless_llm/serve/backends/vllm_backend.py
serverless_llm/serve/controller.py
serverless_llm/serve/model_downloader.py
serverless_llm/serve/sllm_store_manager.py

This PR implements https://github.com/ServerlessLLM/ServerlessLLM/issues/19 by adding vllm / transformers prefix in model save path
+ Modifies the model save path to add backend type prefix.
+ Change the transformers backend load method. Now the transformer backend will load from absolute path in order to prevent the redundant `storage_path` made by `os.join`.
+ Explicitly converting the path to a str is to prevent the grpc proto from being unable to serialize the parameter `model_name_or_path`.

feat: change save model path with backend name

---

serverless_llm/cli/deploy.py

This PR improves the deploy functionality in `sllm-cli` by adding the flexibility to overwrite the default configuration parameters directly through the command line interface. Previously, the CLI only allowed deploying a model using the entire default configuration or a complete custom configuration. Now, users can specify individual configuration parameters to override the defaults.
- Updated `DeployCommand` class in `deploy.py` to accept additional CLI arguments for overriding default configuration parameters:
- `--backend`: Specify the backend to be used, overriding the default backend.
- `--num_gpus`: Specify the required number of GPUs, overriding the default value.
- `--target`: Specify the target concurrency, overriding the default value.
- `--min_instances`: Specify the minimum …

[Feat] Enhance deploy functionality to allow overriding default configuration

---

serverless_llm/cli/deploy.py

This pr fix a minor bug that:
when deploy using config, sllm-cli wrongly shows "deploy none". The model could be successfully deployed.
```
➜   sllm-cli deploy --config config-opt-2.7b.json
INFO 07-30 05:58:36 deploy.py:137] Deploying model None.
INFO 07-30 05:59:41 deploy.py:148] Model registered successfully.
```

fix(cli): display model name when deploy using config

---

serverless_llm/serve/model_downloader.py

As discussed in https://github.com/ServerlessLLM/ServerlessLLM/pull/27, vLLM model downloader will report error when there's other resources using the GPU. This PR could partly fix that problem by setting the GPU block number to 1.
Add three parameters when initialize vLLM model downloader:
`num_gpu_blocks_override` to override the GPU cache block num, avoid reserve lots GPU cache which is actually not used.
`enforce_eager` to avoid capture CUDA graph (which may cost several seconds), since we will not do generate operation in save model.
`max_model_len` to avoid error that GPU cache is not able to contain the model length

fix: vllm model downloader's GPU usage

---

.github/workflows/backend.yaml

This PR changes the condition to trigger the backend test workflow, and only when there's modification under `serverless_llm/serve/backends`, the workflow will be triggered.

fix: backend workflow changes

---

docs/stable/getting_started/installation.md

Add `conda activate sllm-worker` before apply vLLM patch.
Avoid apply vLLM patch in wrong env.

docs: Add Activate Worker Env before Apply vLLM Patch

---

serverless_llm/store/serverless_llm_store/transformers.py

Fix the error report when external tasks occupy the GPUs of the worker node.
Previously it reported that "CPU is not supported in device_map." after computing the device map, which is confusing and not related to the cause that external tasks are using the worker node's GPUs, especially the first GPU. Now it reports "GPU unavailable or not enough GPU memory" which notifies the user that the GPU is under occupation. CPU in device_map checking is moved before the device map computation.

[Fix] Fix gpu unavailable report

---

serverless_llm/serve/model_downloader.py

This pr add code to check if the model exists before starting downloading from the internet to reduce deployment time.
Fixes issue #92.

[FIX] vllm model cache

---

serverless_llm/store/csrc/checkpoint/checkpoint.cpp

Add support for `torch.bfloat16`
Currently, serverless store do not support `torch.bfloat16`, which is the default dtype for llama-3 models. In this PR, we add support for `torch.bfloat16`.

fix: support bfloat16

---

requirements-worker.txt

This PR addresses an urgent issue caused by the recent release of `outlines` v0.1.0 (see [issue #1198](https://github.com/dottxt-ai/outlines/issues/1198)).  
ServerlessLLM depends on `vllm==0.5.0.post1`, which requires `outlines>=0.0.43`. However, the release of `outlines` v0.1.0 introduced a bug that affects compatibility.  
To resolve this, we are explicitly pinning `outlines==0.0.43` in this fix.

FIX: outlines version

---

.github/workflows/publish.yml

- Updated repository URL from test PyPI to the official PyPI in the GitHub Actions workflow.
- Changed secrets to use `SLLM_PYPI` and `SLLM_STORE_PYPI` for publishing packages.
With this pr, we will publish package to pypi officially instead of testpypi from the next release.

build(workflows): update PyPI repository URLs and secrets

---

.github/workflows/publish.yml

Adds `build_and_push_docker` job to automate building and pushing head and worker Docker images with versioned and latest tags.
This PR enhances the CI/CD pipeline by adding a job to automate the Docker image build and push process, ensuring that up-to-date images for both head and worker components are available on Docker Hub after each release. This reduces manual steps, improves deployment consistency, and enables easier image version management.

ci(workflow): add Docker build and push job to publish workflow

---

docs/stable/getting_started/docker_quickstart.md
docs/stable/getting_started/installation.md
docs/stable/store/installation_with_rocm.md
docs/stable/store/quickstart.md
sllm_store/README.md

Corrected the git clone command path in the documentation. Updated from:
`git clone https://github.com/serverless-llm/serverlessllm.git` (i.e., wrong) or `git clone git@github.com:ServerlessLLM/ServerlessLLM.git` (i.e., ssh) to `git clone https://github.com/ServerlessLLM/ServerlessLLM.git` (i.e., https) for consistency.
Ensure the git clone path is accurate and consistent across documentation.

fix: correct git clone path in documentation

---

sllm/serve/controller.py

This PR adds the `control_node` resource to the Ray scheduling options for `store_manager` and `model_loading_scheduler` instances in the `SllmController`. By specifying `control_node` as a required resource, we ensure that these components are scheduled on control nodes rather than worker nodes.
Without this change, `store_manager` and `model_loading_scheduler` could start on worker nodes, which can lead to segmentation faults under [certain conditions](https://github.com/ServerlessLLM/ServerlessLLM/issues/92#issuecomment-2369251289). By enforcing control node scheduling, we improve the reliability of the deployment and prevent these potential crashes.

fix: add control_node resource to Ray components to prevent segfault

---

docs/stable/getting_started/docker_quickstart.md
docs/stable/getting_started/quickstart.md
examples/docker/docker-compose.yml
sllm/serve/backends/transformers_backend.py
sllm/serve/controller.py
tests/backend_test/transformers_backend_test.py

This PR removes the `storage_path` prefix from the transformers backend, aligning the format between model registration and model loading. Models are now referenced uniformly as `backend_name/model_name`.
This change is necessary to address inconsistencies between model registration and model loading paths. By standardizing the path format, it ensures smoother model operations and reduces the likelihood of path mismatches.

[fix] remove storage path from model path in transformer backend

---

examples/docker/README.md
examples/docker/docker-compose.yml

Update docker example, add guidance for specifying GPU devices that worker nodes run on.
Now the docker compose config doesn't support specifying GPU devices to run on for worker nodes.

docs: update Docker to add guide for specifying GPU devices

---

docs/stable/getting_started/docker_quickstart.md

Correct directory name in Docker quickstart documentation:
Standardize to "ServerlessLLM" for consistency across the project.

docs: correct directory name in Docker quickstart documentation

---

sllm/serve/store_manager.py

The dtype of vllm downloader was not assigned correctly, which will cause error when downloading models using vllm backend.
Fix this issue.

fix: Fix dtype error for vllm downloader

---

sllm/cli/default_config.json
sllm/serve/routers/roundrobin_router.py

Add `keep_alive` field in `auto_scaling_config` to let model last for a while after the request is finished.
As it mentioned in #159 , sometimes we want model do not offload immediately when it finished a request, because there may be another request coming soon. `keep_alive` config aims to resolve the problem.
close #159 .
For example, the config below will let model last for 30 seconds after it finished a request, if there is still no new request, then offload.
```json
{
"model": "",
"backend": "vllm",
"num_gpus": 1,
"auto_scaling_config": {
"metric": "concurrency",
"target": 1,
"min_instances": 0,
"max_instances": 10,
"keep_alive": 30
},
"backend_config": {
"pretrained_model_name_or_path": "",
"device_map": "auto",
"torch_dtype": "float16",
"hf_model_class": "AutoModelForCausalLM"
}
} …
```

feat: add keep_alive config

---

sllm/serve/backends/transformers_backend.py
tests/backend_test/transformers_backend_test.py

This PR enhances the Transformers backend to support live migration by:
- **Adding `InferenceStatus` class**: Controls the intermediate status of an inference, records intermediate tokens, and can interrupt the current execution.
- **Using `BackendStatus`**: Manages the backend status (e.g., `UNINITIALIZED`, `RUNNING`), similar to `VllmBackend`.
- **Switching to Ray multi-threading actor**: Replaces async actors since PyTorch is not asyncio-native, making aio-based implementations non-preemptive.
- **Implementing migration-related functions**: Includes `stop`, `shutdown`, `get_current_tokens`, and `resume_kv_cache`.
- **Introducing `resume_generate` function**: Completes the migrated tokens by explicitly using the resumed KV cache, as Transformers currently lack an auto prefix cache. This …

feat(backend): Add InferenceStatus and live-migration support to TransformersBackend

---

docs/stable/cli/cli_api.md
docs/stable/getting_started/quickstart.md
sllm/serve/backends/backend_utils.py
sllm/serve/backends/transformers_backend.py
sllm/serve/backends/vllm_backend.py
sllm/serve/inference_instance.py
sllm/serve/model_downloader.py
sllm/serve/routers/roundrobin_router.py
sllm/serve/store_manager.py
tests/backend_test/transformers_backend_test.py
tests/backend_test/vllm_backend_test.py

Supports configuration of the local model path to omit downloading.
close #128.
Sometimes there is already a local model, or a network problem connecting to HuggingFace, so we want to use local model instead. 
Now we can achieve this by configuring `backend_config.pretrained_model_name_or_path`, it both supports transformers and vllm backends, for example:
```json
{
"model": "facebook/opt-1.3b",
"backend": "transformers",
"num_gpus": 1,
"auto_scaling_config": {
"metric": "concurrency",
"target": 1,
"min_instances": 0,
"max_instances": 10
},
"backend_config": {
"pretrained_model_name_or_path": "/root/users/dblate/facebook/opt-1.3b",
"device_map": "auto",
"torch_dtype": "float16"
}
}
```
Since the pull request contains many file changes, I'd like to state my points:
- In config, `model` and …

feat: support local model path

---

.github/workflows/cli_test.yaml
.github/workflows/pre-commit-format.yml
.github/workflows/publish.yml

* Change the ubuntu version in building sllm-store to 20.04(Previous commit only change the ubuntu version of sllm)
* Add a step to free up github runner space before running docker build and push
Fix the bug of workflow cannot build docker image and sllm-store cannot be run on ubuntu20.04

Free up disk space in github runner and fix build type to ubuntu20.04

---

.github/workflows/publish.yml

This PR integrates both `jlumbroso/free-disk-space@main` and `.github/workflows/scripts/free-disk-space.sh`. By combining these, it is now possible to have up to 49GB of disk space. Additionally, the free-up-space script has been added to all publishing workflows to prevent potential space shortages during execution.
To ensure sufficient disk space for workflows by maximizing available free space.

[build] Enhance Workflow Disk Space Management

---

sllm/serve/model_downloader.py

Change to not use context manager for cache dir of `snapshot_download`.
After merging https://github.com/ServerlessLLM/ServerlessLLM/pull/177 , the vLLM downloader was moved outside the working scope of the context manager of the cache dir. Thus, the input dir will be automatically deleted before we start the vLLM instance, and the user will face an error.
Thus, we remove using with context and manually manage the lifetime of the cache dir.

fix: download vllm model

---

.github/workflows/publish.yml

This PR removes the third-party dependency `jlumbroso/free-disk-space@main` because it deletes the Docker containers that are built for publishing to PyPI.
This change is necessary to prevent the unintended deletion of Docker containers required for the PyPI publishing process.

fix: remove free space to avoid deleting containers

---

sllm/serve/routers/roundrobin_router.py
sllm/serve/utils.py

This closes issue #184.
Fix the `max_queue_length` for model instances, aligning it with the concurrency limit defined in the configuration file.
Add a function in `InstanceHandle` class to check if the current instance can accept one more request. If no slots are available, we will let the next request to go to another instance or wait.

fix: add max queue length

---

examples/embedding/docker-compose.yml
examples/embedding/transformers_backend_example.md
examples/embedding/transformers_embed_config.json
examples/embedding/vllm_backend_example.md
examples/embedding/vllm_embed_config.json
sllm/serve/backends/vllm_backend.py
tests/backend_test/vllm_backend_test.py

Add embedding API using vLLM backend.
The embedding API is currently supported only by the transformers backend. Since vLLM (starting from version 0.4.3) now also supports running embedding models, the corresponding embedding API should be incorporated into sllm as well.

feat: Add embedding model inference for vLLM backend

---

docs/stable/getting_started/docker_quickstart.md
docs/stable/serve/live_migration.md
docs/stable/serve/storage_aware_scheduling.md
examples/docker/README.md
examples/docker/docker-compose.yml
examples/embedding/README.md
examples/embedding/docker-compose.yml
examples/live_migration/README.md
examples/live_migration/docker-compose.yml
examples/storage_aware_scheduling/docker-compose.yml

Updated all `docker compose up` commands to use pre-built Docker images from Docker Hub instead of building locally with the `--build` flag. The official Docker images have been uploaded to Docker Hub: [sllm-worker](https://hub.docker.com/r/serverlessllm/sllm-worker) and [sllm-head](https://hub.docker.com/r/serverlessllm/sllm-head).
Renamed images:
- `serverlessllm/sllm-serve-worker` → `serverlessllm/sllm-worker`
- `serverlessllm/sllm-serve` → `serverlessllm/sllm-head`
This change reduces user testing time by avoiding the need to rebuild images locally.

Docs: use pre-built docker image to ease test

---

README.md
sllm_store/README.md

Fix the link check issue
In our previous document, the link for ROCm support is outdated, which will lead to an link check failure. I've changed all of them to the latest (https://serverlessllm.github.io/docs/stable/store/rocm_quickstart)

fix: link check

---

sllm_store/requirements.txt

Add `peft==0.8.2` into `sllm_store`'s `requirements.txt`
If not, when only install the prebuilt wheel of `sllm_store`, it will not install `peft` and raise an error when trying to save or load model.

fix: sllm_store requirements

---

entrypoint.sh

Remove duplicate vllm patch in `entrypoint.sh`
vllm patch is already applied inside the docker build stage. Thus,`entrypoint.sh`'s apply of it is duplicate and will trigger error when trying to start docker compose.

fix: remove duplicate vllm patch

---

sllm_store/pyproject.toml
sllm_store/requirements-build.txt

Fix the CMake version when build `sllm_store` to set it to less than 4.0.0
Now `pip install cmake` will install `cmake==4.0.0` (https://pypi.org/project/cmake/#history). When building `sllm_store`, it will raise an error: (see https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features)
```
2.275 CMake Error at build/temp.linux-x86_64-cpython-310/_deps/glog-src/cmake/GetCacheVariables.cmake:2 (c
make_policy):
2.275   Compatibility with CMake < 3.5 has been removed from CMake.
2.275
2.275   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
2.275   to tell CMake that the project requires at least <min> but has been updated
2.275   to work with policies introduced by <max> or earlier.
2.275
2.275   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 …
```

fix: set fixed cmake version

---

sllm/serve/store_manager.py
sllm_store/csrc/sllm_store/model.cpp

This PR fixes chunk calculation errors in the `StoreManager`, resolves model unloading issues when using vLLM checkpoints, and corrects the return value of `FreeHost`.
These fixes address critical bugs that impact model management and memory handling, particularly when working with vLLM with storage-aware scheduler.

Fix chunk calculation and vLLM model unloading bugs in StoreManager

---

.github/workflows/cli_test.yaml
.github/workflows/linters.yml
.github/workflows/pre-commit-format.yml

Updated GitHub Actions workflows by replacing ubuntu-20.04 with ubuntu-latest to resolve CI job failures due to deprecated environments.
CI checks were failing or getting cancelled because GitHub has deprecated the `ubuntu-20.04` runner. This change ensures that all CI jobs run on the supported `ubuntu-latest` environment.

fix: update ubuntu-20.04 to ubuntu-latest in workflows

---

.github/workflows/docs-validation.yml

Add GitHub Actions workflow to validate documentation builds before merging PRs.
Previously, documentation changes were copied to the target repository (serverlessllm.github.io) without validation, which could lead to build failures and broken documentation. This workflow prevents invalid documentation from being merged by testing the build process against the Docusaurus configuration in the target repository.

ci(docs): add documentation build validation workflow

---

docs/stable/deployment/single_machine.md
docs/stable/store/quickstart.md

Update vllm version in quick start doc
Clarify the vllm patch version (0.9.0.1 rather than 0.6.6).

fix: update vllm version in quick start doc

---

docs/stable/features/quantized_models.md
docs/stable/store/quantization.md
sllm_store/sllm_store/utils.py

Re-adding from_dict() method to quantization logic to allow sllm-cli quantization.
Adds back accidentally removed code.

fix: re-adding sllm-cli quant logic from sllm_store accidentally removed last commit

---

.github/workflows/rocm_test.yaml
sllm_store/CMakeLists.txt
sllm_store/cpp_build.sh
sllm_store/tests/cpp/CMakeLists.txt

C++ tests are now produced and ran, and no more include errors in them
It fixed the existing issue of tests producing a `No tests were found!!!` error from ctest

fix: sllm_store_tests (C++) were not running
